[workspace]
resolver = "2"
members = [
    "contracts/zkstash",
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
strip = true
lto = true
codegen-units = 1
panic = "abort"

[workspace.package]
authors = ["LexaPay Developers <dev@lexapay.org>"]
homepage = "https://lexapay.org"
